# TYPE WALLET MODE
TYPE_WALLET = "argent"  # argent/braavos

# RANDOM WALLETS MODE
RANDOM_WALLET = True  # True/False

SLEEP_FROM = 100
SLEEP_TO = 600

QUANTITY_THREADS = 10

THREAD_SLEEP_FROM = 5
THREAD_SLEEP_TO = 5

# GWEI CONTROL MODE
CHECK_GWEI = True
MAX_GWEI = 25

# RETRY MODE
RETRY_COUNT = 3

# CAIRO VERSION CONTROL
CAIRO_VERSION = 0

FEE_MULTIPLIER = 1.5
