# TYPE WALLET MODE
TYPE_WALLET = "argent"  # argent/braavos

# RANDOM WALLETS MODE
RANDOM_WALLET = True  # True/False

# removing a wallet from the list after the job is done
REMOVE_WALLET = False

SLEEP_FROM = 350
SLEEP_TO = 550

QUANTITY_THREADS = 1

THREAD_SLEEP_FROM = 150
THREAD_SLEEP_TO = 450

# GWEI CONTROL MODE
CHECK_GWEI = False
MAX_GWEI = 30

# RETRY MODE
RETRY_COUNT = 3

# CAIRO VERSION CONTROL
CAIRO_VERSION = 0

FEE_MULTIPLIER = 1.5
